## Numpy

- Creating arrays
- Multi-dimentional arrays
- Randomly generated arrays
- Element-wise operations
  - Comparison operations
  - Logical operations
- Summarizing operations

In [1]:
# import numpy
import numpy as np

### Creating arrays

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

In [5]:
# fill arrays with an arbitrary number
# np.full(size, number)
np.full(4, 3.14)

array([3.14, 3.14, 3.14, 3.14])

In [7]:
a = np.array([1, 2, 3, 4, 12, 13, 14, 15])
a

array([ 1,  2,  3,  4, 12, 13, 14, 15])

In [8]:
# Access array elements
a[3]

4

In [9]:
# Change element
a[3] = 101
a

array([  1,   2,   3, 101,  12,  13,  14,  15])

In [13]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [20]:
# Create numbers within set parameters
# np.linespace(first_number, last_number, size)
np.linspace(1,81,9)

array([ 1., 11., 21., 31., 41., 51., 61., 71., 81.])

### Multi-dimentional arrays


In [21]:
# np.zeros((# rows, # columns))
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
n = np.array([
    [1,2,3],
    [3,2,1],
    [7,7,9]
],dtype=object)


In [35]:
n

array([[1, 2, 3],
       [3, 2, 1],
       [7, 7, 9]], dtype=object)

 Access elements in the array

i -> rows
j -> columns

```
 0i[1,2,3]
 1i[3,2,1]
 2i[7,7,9]
   0j 1j 2j
```

In [37]:
print(n[0,0])
print(n[0,1])
print(n[0,2])

1
2
3


In [38]:
# Accessing rows only
n[2]

array([7, 7, 9], dtype=object)

In [39]:
n[2] = [56,5,76]

In [40]:
n

array([[1, 2, 3],
       [3, 2, 1],
       [56, 5, 76]], dtype=object)

In [41]:
# Accessing columns
n[:, 0]

array([1, 3, 56], dtype=object)

In [42]:
n[:, 0] = [9,4,5]
n

array([[9, 2, 3],
       [4, 2, 1],
       [5, 5, 76]], dtype=object)

## Randomly generate arrays

In [46]:
# np.random.rand(#rows, #columns)
n = np.random.rand(4, 3)
n

array([[0.62133063, 0.55676756, 0.66937043],
       [0.63273124, 0.50021846, 0.55940375],
       [0.61207599, 0.10840914, 0.46379462],
       [0.5074694 , 0.5697021 , 0.80335044]])

In [53]:
# remove randomness

# sample from the uniform distribution
np.random.seed(2)
np.random.rand(4,3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209]])

In [54]:
# sample from the normal distribution
np.random.seed(2)
# np.randon.randn()
np.random.randn(4,3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801]])

In [55]:
# generate random integers
np.random.seed(2)
np.random.randint(low=0, high=100, size=(4,3))

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75]])

## Element-wise operations

In [57]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [58]:
a + 1

array([1, 2, 3, 4, 5])

In [59]:
a * 2

array([0, 2, 4, 6, 8])

In [60]:
a / 2 

array([0. , 0.5, 1. , 1.5, 2. ])

In [64]:
b = (10 * ((a*2))**2 / 100)
b

array([0. , 0.4, 1.6, 3.6, 6.4])

In [65]:
a + b

array([ 0. ,  1.4,  3.6,  6.6, 10.4])

## Comparison operations

In [67]:
a

array([0, 1, 2, 3, 4])

In [66]:
a >= 2

array([False, False,  True,  True,  True])

In [68]:
b

array([0. , 0.4, 1.6, 3.6, 6.4])

In [69]:
a > b

array([False,  True,  True, False, False])

In [70]:
# return true condition
a[a>b]


array([1, 2])

## Summarizing operations

- min
- avg
- sum
- std

In [71]:
a.min()

0

In [72]:
a.max()

4

In [73]:
a.sum()

10

In [74]:
n.min()

0.10840913795603868

In [75]:
n.max()

0.8033504430561516

In [76]:
n.std()

0.15849900745777618