## Vector operations

In [2]:
import numpy as np

In [3]:
u = np.array([2,4,5,6])


In [4]:
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1,0,0,2])

In [6]:
# Addition
u+v

array([3, 4, 5, 8])

In [7]:
# Subtraction
u-v

array([1, 4, 5, 4])

In [8]:
# Multiplication
u*v

array([ 2,  0,  0, 12])

### Vector-vector multiplication4 (dot product)

In [9]:
u.shape[0]

4

In [10]:
v.shape[0]

4

In [11]:
def vector_vector_multiplication(u, v):
    # make sure v & u have same size
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result += u[i] * v[i]
    
    return result

In [12]:
vector_vector_multiplication(u, v)

14.0

In [13]:
u.dot(v)

14

### Matrix-vector multiplication

In [14]:
U = np.array([
    [2.0,4.0,5.0,6.0],
    [1.0,2.0,1.0,2.0],
    [3.0,1.0,2.0,1.0]
])

In [15]:
U

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [16]:
U.shape

(3, 4)

In [17]:
v.shape

(4,)

# Matrix-vector multiplication


```rm
     U       v
[---Uo----]  [|]    [UoTv]
[---------]  [|]    [  | ]
[---------]  [v] =  [  | ]
[---------]  [|]    [  | ]
[---Uk-1--]  [|]    [Uk-1Tv]
```
```


In [18]:
def matrix_vector_multiplication(U, v):
    # row vector dimensions are similar
    assert U.shape[1] == v.shape[0]
    
    # number of rows
    num_rows = U.shape[0]
    
    # result vector
    # dim is # of rows
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    
    return result

In [19]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [20]:
U.dot(v)

array([14.,  5.,  5.])

### Matrix-matrix multiplication

```
    U        V            UV
[2,4,5,6]  [1 1   2]    [ |    |     |]
[1,2,1,2]  [0 0.5 1] =  [UV0  UV1  UV2]
[3,1,2,1]  [0 2   1]    [ |    |     |]
           [0 1   1]
```

In [21]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [22]:
V.shape[0]

4

In [23]:
U.shape[1]

4

In [24]:
U

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [25]:
def matrix_matrix_multiplication(U,V):
    # Check if we can multiply row of U
    # and column of V
    assert U.shape[1] == V.shape[0]
    
    # Create a new matrix
    # initialize with zero
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:, i] = Uvi
        
    return result

In [26]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [27]:
M = U.dot(V)
M


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

Denoted I

```
[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]
```

U.I = U <br>
I.U = U

In [28]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
M 

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [31]:
M.dot(I)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [32]:
I.dot(M)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Matrix inverse

In [33]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [34]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [35]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])